version: '3.8'

services:
  # Redis service
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"  # Map host 6380 to container 6379
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Main server
  server:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy
    command: node src/server.js

  # Email worker
  worker:
    build: .
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy
    command: node src/workers/emailWorker.js
    deploy:
      replicas: 1  # Change this to run multiple workers

volumes:
  redis-data: